### ISSUE TITLE
Diacritical characters causing errors

### ISSUE THREAD

**Issue by pdoelwijt** [Tools4everBV/HelloID-Conn-Prov-Target-Iprotect#1]
The protect connector does not proces diacritical characters correctly (they are shown as a question mark: Ang�lique).
(examples of words that will cause errors: Mariëlle, André, Çaglayan, microbiologie & Immunologie, van 't)
Because iprotect use sql in the http post, you'll need to escape the single quote for example, by a function

	function replace-singleQute { 
	Param ([string]$string)
	$string -replace "'","\'" }

Diacritical characters, 
To resolve this issue, change the encoding.

Example

 $body = "Mariëlle & André"
 $splatParams = @{
        Uri                = "$($config.BaseUrl)/xmlsql"
        Method             = 'POST'
        Headers            = @{'Accept' = 'text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2'; 'Cookie' = $JSessionID }
        UseBasicParsing    = $true
        MaximumRedirection = 0
        ContentType        = 'text/xml;charset=ISO-8859-1'
        Body               = $Body
        WebSession         = $script:WebSession
    }

Change the encoding to HTML

$body = "Mariëlle & André"
$bodyEncoded = [System.Web.HttpUtility]::HtmlEncode($string)  
	other encoding option are $bodyEncoded = [System.Text.Encoding]::UTF8.GetBytes($body) or $bodyEncoded = [System.Text.Encoding]::ASCII.GetBytes($body) 

 $splatParams = @{
        Uri                = "$($config.BaseUrl)/xmlsql"
        Method             = 'POST'
        Headers            = @{'Accept' = 'text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2'; 'Cookie' = $JSessionID }
        UseBasicParsing    = $true
        MaximumRedirection = 0
        ContentType        = 'text/xml;charset=ISO-8859-1'
        Body               = $bodyEncoded
        WebSession         = $script:WebSession
    }

**Comment by JeroenBL** [comment]
This issue has been open for quite some time without any recent activity. We appreciate all the feedback and contributions.

To keep our issue tracker focused and organized, we are closing this issue. If the problem persists or if there are any new developments, please feel free to reopen the issue or create a new one
